# Generated 2026-06-24 13:56:17 ??? LAN IP: 192.168.254.154
# Xubuntu: sudo cp deploy/dnsmasq/stratacore.conf /etc/dnsmasq.d/stratacore.conf && sudo systemctl restart dnsmasq

address=/stratacore.tech/192.168.254.154
address=/api.stratacore.tech/192.168.254.154
address=/admin.stratacore.tech/192.168.254.154
address=/guest.stratacore.tech/192.168.254.154
address=/ocpp.stratacore.tech/192.168.254.154
