# Generated 2026-06-25 12:46:19 ??? LAN IP: 192.168.137.2
# Xubuntu: sudo cp deploy/dnsmasq/stratacore.conf /etc/dnsmasq.d/stratacore.conf && sudo systemctl restart dnsmasq

address=/stratacore.tech/192.168.137.2
address=/api.stratacore.tech/192.168.137.2
address=/admin.stratacore.tech/192.168.137.2
address=/guest.stratacore.tech/192.168.137.2
address=/ocpp.stratacore.tech/192.168.137.2
